### ISSUE TITLE
document

### ISSUE THREAD

**Issue by parhamsagharchi** [FMFigueroa/superheroes#1]
Hi,

I would like to say thanks for your codes, I adore it because it has lots of benefits methods such as redux and next-auth.
I read 50% of your code about this project and I really need to have a document to figure out the whole of your project and the architecture of your code.

so, to sum up I am going to asking to write a pdf with 1 or 2 pages to describe the whole structure.

your sincerely,

Parham

**Comment by FMFigueroa** [comment]
HI , I'm glad you can rate it, I'm going to write a more detailed readme.md to have a better understanding of the folder structure, however, feel free to ask me, I'll gladly help you solve your doubts, follow me on LinkedIn and we'll stay that way connected, greetings ..!

**Comment by parhamsagharchi** [comment]
Thanks alot
